import { FormCategoryDefinition } from '../types';

export const DOCUMENT_CATEGORIES: FormCategoryDefinition[] = [
  {
    id: 'bank_statements',
    number: 1,
    title: 'Bank Statements',
    description: 'Upload PDF, Excel, or CSV bank statements covering the bookkeeping period.',
    uploadLabel: 'Upload Bank Statements',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Please use the primary business account ending in 4321.',
  },
  {
    id: 'credit_cards',
    number: 2,
    title: 'Credit Card Statements',
    description: 'Upload business credit card monthly statements and breakdown reports.',
    uploadLabel: 'Upload Credit Card Statements',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'No business credit card was used during this period.',
  },
  {
    id: 'sales_invoices',
    number: 3,
    title: 'Sales Invoices, Receipts & Payouts',
    description: 'Upload sales invoices issued to customers, stripe/paypal payout reports, and sales receipts.',
    uploadLabel: 'Upload Sales Invoices / Receipts / Payout Reports',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Includes Stripe payout summary for August.',
  },
  {
    id: 'purchase_bills',
    number: 4,
    title: 'Purchase Bills',
    description: 'Upload supplier invoices, bills, and trade accounts payable records.',
    uploadLabel: 'Upload Purchase Bills / Supplier Invoices',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Includes stock purchase invoice from main distributor.',
  },
  {
    id: 'expense_bills',
    number: 5,
    title: 'Expense Bills & Receipts',
    description: 'Upload utility bills, software subscriptions, office expenses, and business receipts.',
    uploadLabel: 'Upload Expense Bills / Receipts',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Software and hosting receipts attached.',
  },
  {
    id: 'expense_claims',
    number: 6,
    title: 'Expense Claims',
    description: 'Upload employee or director out-of-pocket expense claim forms and supporting receipts.',
    uploadLabel: 'Upload Expense Claims & Supporting Receipts',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Director travel expense claim for August client meetings.',
  },
  {
    id: 'petty_cash',
    number: 7,
    title: 'Petty Cash Expenses',
    description: 'Upload petty cash tin logs, till vouchers, and cash receipts.',
    uploadLabel: 'Upload Petty Cash Records / Receipts',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Petty cash log balanced as of month end.',
  },
  {
    id: 'payroll',
    number: 8,
    title: 'Payroll Reports',
    description: 'Upload HMRC FPS / EPS reports, Full Payment Summaries, and monthly pay slips.',
    uploadLabel: 'Upload FPS / EPS / Full Payment Summary / Payroll Reports',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'No employees on payroll during this period.',
  },
  {
    id: 'pension_reports',
    number: 9,
    title: 'Workplace Pension Reports',
    description: 'Upload monthly Nest, Aviva, People’s Pension, or Smart Pension contribution schedules.',
    uploadLabel: 'Upload Workplace Pension Reports',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Nest pension submission confirmation attached.',
  },
  {
    id: 'vat_records',
    number: 10,
    title: 'VAT Records',
    description: 'Upload MTD VAT calculation sheets, EC Sales lists, and HMRC VAT returns.',
    uploadLabel: 'Upload VAT Records / VAT Reports / Supporting Documents',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Q3 VAT calculation breakdown attached.',
  },
  {
    id: 'loans_hp',
    number: 11,
    title: 'Loan / Hire Purchase Agreements',
    description: 'Upload bank loan schedules, equipment finance agreements, and vehicle HP statements.',
    uploadLabel: 'Upload Loan / Hire Purchase Agreement & Statements',
    notesLabel: 'Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Van HP monthly statement.',
  },
  {
    id: 'additional_docs',
    number: 12,
    title: 'Additional Documents',
    description: 'Upload any other relevant accounting, tax, or legal documents for your bookkeeper.',
    uploadLabel: 'Upload Any Other Relevant Documents',
    notesLabel: 'Additional Notes for Bookkeeper',
    supportedFormats: ['PDF', 'JPG', 'JPEG', 'PNG', 'WEBP', 'XLS', 'XLSX', 'CSV', 'ZIP'],
    allowsMultiple: true,
    allowsNA: true,
    exampleNotes: 'Dividend vouchers or year-end adjustments.',
  },
];
